# configuration for master/CI branch
-
  branches:
    only:
      - master

  os: Visual Studio 2017 Preview
  configuration: Release
  environment:
    LIB_VERSION: '0.9.0' 
  build_script:
  - ps: .\build.ps1
  build:
    project: Scorpion.Driver.sln
    verbosity: minimal
  artifacts:
  - path: '**\Kbiosystems.Scorpion.Driver.*.nupkg'

  version: 0.9.0-ci{build}
  deploy:
  - provider: NuGet
    api_key:
      secure: dsbeCFKqWtfS6hXyzapgVEkVbh6o0TQpW6CfuNGuYDvKCu2b7cW8i3vi5b8/sIi7
