# configuration for master/CI branch
-
  branches:
    only:
      - master

  os: Visual Studio 2017
  configuration: Release
  environment:
    LIB_VERSION: '0.9.0' 
  before_build: 
    - ps: .\install.ps1
  build_script:
  - ps: .\build.ps1
  build:
    project: Scorpion.Driver.sln
    verbosity: minimal
  artifacts:
  - path: '**\Kbiosystems.Scorpion.Driver.*.nupkg'

  version: 0.9.0-ci{build}
  deploy:
  - provider: NuGet
    api_key:
      secure: need this still
